bar {
    swaybar_command bash -c 'exec flock -n ~/.cache/waybar.lock bash -c "pkill -x waybar; while pgrep -x waybar >/dev/null; do sleep 0.1; done; exec waybar"'
    position top
    hidden_state hide
    mode dock
    modifier Mod4
}
