# Init programs
# Check with: journalctl -t sway-autostart --no-pager

exec systemctl --user start sway-xdg-autostart.target 2>&1 | systemd-cat -t sway-autostart

#exec dbus-update-activation-environment --systemd DISPLAY WAYLAND_DISPLAY SWAYSOCK
exec echo "*.dpi: 130" | xrdb -merge 2>&1 | systemd-cat -t sway-autostart
#exec rclone mount gdrive: ~/gdrive/gdrive/

exec rm -f ~/*.tmp 2>&1 | systemd-cat -t sway-autostart
exec rm -f ~/*.swp 2>&1 | systemd-cat -t sway-autostart
#exec sudo virsh net-list
exec toolbox run trash-empty -f 5 2>&1 | systemd-cat -t sway-autostart
exec podman system prune -f --external 2>&1 | systemd-cat -t sway-autostart
exec podman system prune -f --volumes --filter label!=com.github.containers.toolbox 2>&1 | systemd-cat -t sway-autostart
# https://github.com/ghostty-org/ghostty/discussions/8475
# https://github.com/ghostty-org/ghostty/discussions/8899
exec env GTK_IM_MODULE=simple ghostty --gtk-single-instance=true --quit-after-last-window-closed=false --initial-window=false 2>&1 | systemd-cat -t sway-autostart
# https://github.com/ghostty-org/ghostty/discussions/12181
exec ~/dev/dotfiles/sway/scripts/ghostty-paste.sh
