theme = "onedark"

[editor]
line-number = "relative"
cursorline = true
bufferline = "multiple"

[editor.lsp]
display-inlay-hints = true

[editor.cursor-shape]
insert = "bar"

[keys.normal]
C-right = "move_next_word_start"
C-left = "move_prev_word_end"
A-left = "move_prev_word_start"
A-right = "move_next_word_end"
S-left = "extend_char_left"
S-right = "extend_char_right"
S-A-left = "extend_prev_word_start"
S-A-right = "extend_next_word_start"

[keys.insert]
C-right = "move_next_word_start"
C-left = "move_prev_word_end"
A-left = "move_prev_word_start"
A-right = "move_next_word_end"
S-left = "extend_char_left"
S-right = "extend_char_right"
S-A-left = "extend_prev_word_start"
S-A-right = "extend_next_word_start"
