source ~/.vim/plugins.vim  " Keep it first, if not requires will fail
source ~/.vim/keys.vim
source ~/.vim/lsp.lua
source ~/.vim/mouse.vim
"source ~/.vim/ocaml.vim
source ~/.vim/repl.lua
source ~/.vim/search.vim
source ~/.vim/telescope.lua
source ~/.vim/trailing.vim
source ~/.vim/ui.vim

" Read let bindings: echo $var
" Read set bindings: echo &$var
" Read set boolean bindings no$var: echo&$var

set nowrap
set smartindent

"set ts=3                 " Tabulación de 3 caracteres
"set sw=3                 " Identado de 3 caracteres
set expandtab            " Cambia los tabs por espacios

"filetype indent on      " Enabled by sensible. Only needed for vim

" Back to NORMAL mode when terminal window loses focus
autocmd FocusLost * call feedkeys("\<esc>")
"autocmd FocusLost * if mode()[0] =~ 'i\|R' | call feedkeys("\<esc>") | endif

" Stay in the same place when leaving insert mode
" Does not work for a (https://vim.fandom.com/wiki/Prevent_escape_from_moving_the_cursor_one_character_to_the_left#Limitation)
"inoremap <silent> <Esc> <C-O>:stopinsert<CR> "
"auto InsertLeave * call feedkeys("\<Right>")
set ve+=onemore      " Additional char at the end of line

autocmd TermOpen * setlocal nonumber norelativenumber
