source ~/.vim/plugins.vim  " Keep it first, if not requires will fail
source ~/.vim/bufferline.lua
source ~/.vim/commenter.vim
source ~/.vim/format.vim
source ~/.vim/keys.vim
source ~/.vim/lsp.lua
source ~/.vim/mouse.vim
source ~/.vim/nvimtree.lua
"source ~/.vim/ocaml.vim
source ~/.vim/repl.lua
source ~/.vim/search.vim
source ~/.vim/scrollbar.lua
source ~/.vim/statusline.lua
source ~/.vim/telescope.lua
source ~/.vim/ui.vim

" Read let bindings: echo $var
" Read set bindings: echo &$var
" Read set boolean bindings no$var: echo&$var

set nowrap
set smartindent

set ts=2                 " Tabs
set sw=2                 " Indents
set expandtab            " Fills tabs with spaces

"filetype indent on      " Enabled by sensible. Only needed for vim

" Back to NORMAL mode when terminal window loses focus
"autocmd FocusLost * call feedkeys("\<esc>")
"autocmd FocusLost * if mode()[0] =~ 'i\|R' | call feedkeys("\<esc>") | endif

" Stay in the same place when leaving insert mode
" Does not work for a (https://vim.fandom.com/wiki/Prevent_escape_from_moving_the_cursor_one_character_to_the_left#Limitation)
"inoremap <silent> <Esc> <C-O>:stopinsert<CR> "
"auto InsertLeave * call feedkeys("\<Right>") " breaks mayus select
set ve+=onemore      " Additional char at the end of line

set undodir=~/.vimundodir
set undofile

set directory=.
