alias k=kubectl
alias d=docker
alias watch="watch "
alias ls="ls --color -B"
alias grep="grep --color"
alias grepi="grep --color -i"
alias grepri="grep --color -ri"
alias g=grep
alias gi=grepi
alias gri=grepri
alias c=cat
alias ll='ls -lFh'
alias la='ls -A'
alias l='ls'
alias cd..='cd ..'
alias ..='cd ..'
alias ...='cd ../../'
alias ....='cd ../../..'
alias cd-='cd -'
alias cd--='cd --'
alias code='flatpak run com.visualstudio.code'
alias v=vi
alias vim=vi
alias open=xdg-open
alias o=xdg-open
