#!/bin/sh

ln -s $(pwd)/../bash/bash_logout ~/.bash_logout
ln -s $(pwd)/../bash/bashrc.d ~/.bashrc.d
ln -s $(pwd)/../containers ~/.config/containers
ln -s $(pwd)/../code/keybindings.json ~/.var/app/com.visualstudio.code/config/Code/User/
ln -s $(pwd)/../code/keybindings.json ~/.config/Cursor/User/
ln -s $(pwd)/../code/settings.json ~/.var/app/com.visualstudio.code/config/Code/User/
ln -s $(pwd)/../code/settings.json ~/.config/Cursor/User/
ln -s ~/.var/app/com.visualstudio.code/data/vscode/extensions/ ~/.cursor
ln -s $(pwd)/../desktop ~/.local/share/applications
ln -s $(pwd)/../docker ~/.config/docker
#ln -s $(pwd)/../dropbox/status ~/.local/share/flatpak/exports/share/icons/hicolor/16x16
ln -s $(pwd)/../dunst ~/.config/dunst
#ln -s $(pwd)/../emacs/emacs ~/.emacs
#ln -s $(pwd)/../emacs/emacs.d ~/.emacs.d
ln -s $(pwd)/../flatpak/overrides ~/.local/share/flatpak
ln -s $(pwd)/../foot ~/.config/foot
ln -s $(pwd)/../gcalcli ~/.config/gcalcli
ln -s $(pwd)/../git/gitconfig ~/.gitconfig
ln -s $(pwd)/../git/gitignore_global ~/.gitignore_global
ln -s $(pwd)/../gnome/texteditor/keyfile ~/.var/app/org.gnome.TextEditor/config/glib-2.0/settings/keyfile
#ln -s $(pwd)/gnome/nautilus/scripts ~/.local/share/nautilus
ln -s $(pwd)/../gtk-3.0 ~/.config
ln -s $(pwd)/../helix ~/.var/app/com.helix_editor.Helix/config
#ln -s $(pwd)/../icons/hicolor/256x256/apps/claude-desktop.png ~/.local/share/flatpak/exports/share/icons/hicolor/256x256/apps/claude-desktop.png
ln -s $(pwd)/../icons/hicolor/256x256/apps/co.anysphere.cursor.png ~/.local/share/flatpak/exports/share/icons/hicolor/256x256/apps/co.anysphere.cursor.png
ln -s $(pwd)/../imv ~/.config
ln -s $(pwd)/../mcp.json ~/.cursor
ln -s $(pwd)/../mimeapps.list ~/.config
ln -s $(pwd)/../mpv/mpv.conf ~/.var/app/io.mpv.Mpv/config/mpv/mpv.conf
ln -s $(pwd)/../mpv/input.conf ~/.var/app/io.mpv.Mpv/config/mpv/input.conf
ln -s $(pwd)/../rofi ~/.config/rofi
ln -s $(pwd)/../starship.toml ~/.config/starship.toml
ln -s $(pwd)/../sway ~/.config/sway
ln -s $(pwd)/../swaync ~/.config/swaync
#ln -s $(pwd)/../systemd/power-monitor.service ~/.config/systemd/user/power-monitor.service
#ln -s $(pwd)/../systemd/power_monitor.sh ~/.config/systemd/user/power_monitor.sh
ln -s $(pwd)/../tmux.conf ~/.tmux.conf
#ln -s $(pwd)/../vim/gvimrc ~/.gvimrc
ln -s $(pwd)/../vim/vimrc ~/.vimrc
ln -s $(pwd)/../vim/vimrc ~/.var/app/io.neovim.nvim/config/nvim/init.vim
ln -s $(pwd)/../vim/vim ~/.vim
ln -s $(pwd)/../vim/vim/ftplugin ~/.var/app/io.neovim.nvim/config/nvim/ftplugin
ln -s $(pwd)/../waybar ~/.config/waybar
ln -s $(pwd)/../wezterm.lua ~/.wezterm.lua
ln -s $(pwd)/../xfce4/xfconf ~/.config/xfce4
#ln -s $(pwd)/../zathura ~/.config/zathura
