alias ....='cd ../../..'
alias ...='cd ../../'
alias ..='cd ..'
alias -- -='cd -'
alias c=cat
alias cat='bat -p -P'
alias cd--='cd --'
alias cd-='cd -'
alias cd..='cd ..'
alias cn='cat -n'
alias code='flatpak run --socket=wayland com.visualstudio.code --ozone-platform-hint=wayland'
alias d=docker
alias emacs='flatpak run org.gnu.emacs'
alias g=grep
alias gi=grepi
alias grep='grep --color'
alias grepi='grep --color -i'
alias grepri='grep --color -ri'
alias gri=grepri
alias gvim='flatpak run org.vim.Vim'
alias h=head
alias k=kubectl
alias l='ls'
alias la='ls -A'
alias ll='ls -lFh'
alias ls='ls --color -B'
alias o=open
alias open=xdg-open
alias p=podman
alias rm=trash
alias t=toolbox
alias vi='flatpak run io.neovim.nvim'
alias v=vi
alias vim=vi
alias watch='watch '
