# -*- conf -*-

term=xterm-256color
pad=4x4
resize-by-cells=no

#font=monospace:size=15
font=JetBrains Mono:size=14, Noto Color Emoji:size=14

[mouse]
hide-when-typing=yes

[scrollback]
lines=10000
multiplier=10.0

[key-bindings]
scrollback-up-half-page=Control+Shift+Up
scrollback-down-half-page=Control+Shift+Down
scrollback-up-page=Control+Shift+Page_Up
scrollback-down-page=Control+Shift+Page_Down
scrollback-home=Shift+Home
scrollback-end=Shift+End

[search-bindings]
find-prev=Up
find-next=Down

[text-bindings]
\x1b\x0d = Shift+Return

# Matches ghostty's default color scheme (background/foreground/palette)
[colors-dark]
foreground=ffffff
background=282c34

regular0=1d1f21
regular1=cc6666
regular2=b5bd68
regular3=f0c674
regular4=81a2be
regular5=b294bb
regular6=8abeb7
regular7=c5c8c6

bright0=666666
bright1=d54e53
bright2=b9ca4a
bright3=e7c547
bright4=7aa6da
bright5=c397d8
bright6=70c0b1
bright7=eaeaea
